### ISSUE TITLE
Change banner metadata img.

### ISSUE THREAD

**Issue by fiqryq** [ThangHuuVu/thvu-blog#112]
#ASK
Hello i want to ask how to change banner metadata on index?
banner on index : 
<img width="309" alt="Screen Shot 2021-12-19 at 09 08 59" src="https://user-images.githubusercontent.com/25787603/146661099-1e0a2103-dee5-4698-9305-e131e2cc77a7.png">

banner on other page :
<img width="310" alt="Screen Shot 2021-12-19 at 09 10 37" src="https://user-images.githubusercontent.com/25787603/146661112-8fbb0a2a-55ff-47a6-8490-8bd081a591c8.png">

This my code : 
```js
const siteMetadata = {
  title: 'Fiqry choerudin',
  author: 'Fiqry choerudin',
  headerTitle: '',
  description:
    'I was born in 1999. Being programmer since college in University. working as Frontend Developer. love making open source projects on Github.',
  language: 'en-us',
  siteUrl: 'https://fiqrychoerudin.dev/',
  siteRepo: 'https://github.com/fiqryq/Fiqrychoerudin.dev',
  siteLogo: '/public/static/images/avatar.png',
  image: '/static/images/avatar.png',
  socialBanner: '/static/images/social-banner.png',
  email: 'halo@fiqrychoerudin.dev',
  github: 'https://github.com/fiqryq',
  twitter: 'https://twitter.com/fiqryq_',
  facebook: 'https://facebook.com/fiqryq',
  youtube: 'https://youtube.com',
  linkedin: 'https://www.linkedin.com/fiqrychoerudin',
  locale: 'en-US',
  },
}
```

**Comment by ThangHuuVu** [comment]
Hi @fiqryq, I think this is a cache issue. I checked your site at https://www.opengraph.xyz/url/https%3A%2F%2Ffiqrychoerudin.dev/ and it seems normal. If you are using the same project template as I am then changing `socialBanner` is enough.

**Comment by fiqryq** [comment]
> Hi @fiqryq, I think this is a cache issue. I checked your site at https://www.opengraph.xyz/url/https%3A%2F%2Ffiqrychoerudin.dev/ and it seems normal. If you are using the same project template as I am then changing `socialBanner` is enough.

ahh I see thank you so much for telling me, I'm so confused because my banner won't change haha. thank you btw
