### ISSUE TITLE
Ask background blur error on chrome

### ISSUE THREAD

**Issue by fiqryq** [ThangHuuVu/thvu-blog#114]
hello, I want to ask something, how do you implement backdrop-filter blur on your navbar? I use backdrop-filter blur and my navbar gets bug but only happens on chrome browser.

https://user-images.githubusercontent.com/25787603/147182121-34a34d0d-34bb-4c0e-9bb9-0c60cce46d12.mov

**Comment by ThangHuuVu** [comment]
Hi, the blurred background is just CSS. You can check my implementation using TailwindCSS in `components/Header.tsx`. If you are still unsure where to fix the problem on your side, check these resources:
- Official TailwindCSS: https://tailwindcss.com/docs/backdrop-blur
- https://braydoncoyer.dev/blog/build-a-glassmorphic-navbar-with-tailwindcss-backdrop-filter-and-backdrop-blur 

A note: I'd rather keep GitHub issues for the actual issues related to this repo, so in the future, if you want to reach out for implementation questions, DM me on Twitter. I'm [@thanghvu ](https://twitter.com/thanghvu). I'll be happy to help there!
